### PR TITLE
Add preliminary support for Python 3.12a7.

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by icemac** [comment]
o no, we have breaking tests on Python 3.12a7.

**Comment by dataflake** [comment]
The issues are described at https://github.com/zopefoundation/meta/issues/181. Both `zc.buildout` and `setuptools` are at fault but there is no reaction to the issues I have filed.

The only suggestion I have would be to not install `zope.proxy` via `setup_requires` to get at the C header files, but to just copy them straight into `zope.security`. This has the drawback of them going out of sync with `zope.proxy` but I think it would get rid of the build issue. Or maybe there's a saner way to get at those header files during the build.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2023-4-17 23:50 -0700:
>The issues are described at https://github.com/zopefoundation/meta/issues/181. Both `zc.buildout` and `setuptools` are at fault but there is no reaction to the issues I have filed.

The `test (3.12.0-alpha.7, ubuntu-20.04)` is also failing
which likely is not Mac related and likely not due to `setuptools/buildout`
problems.

**Comment by dataflake** [comment]
> The `test (3.12.0-alpha.7, ubuntu-20.04)` is also failing which likely is not Mac related and likely not due to `setuptools/buildout` problems.

This is already understood. The issue I am talking about cropped up at https://github.com/zopefoundation/AccessControl/pull/139. I think the way dependency header files are provided before the build step in some packages is the problem. Packages that have a copy of their dependencies' headers don't show the issue.

**Comment by icemac** [comment]
@dataflake wrote:
> The only suggestion I have would be to not install `zope.proxy` via `setup_requires` to get at the C header files, but to just copy them straight into `zope.security`

I implemented this in #98. I am planning to release that changes as a dev version as some tests break but it should unblock us in AccessControl.

**Comment by icemac** [comment]
Superseded by #98.

**Pull request closed without merging**
