### PR TITLE
Fix GHA Python 3.10 build on MacOS

### PR DESCRIPTION
**Pull request by icemac**
Using a setuptools version which worked up to last week.

Goal is to fix https://github.com/zopefoundation/zope.security/runs/6961463587?check_suite_focus=true

Locally the problem does not occur when running the tests using `tox`.

### CODE REVIEW

**Comment by icemac** [comment]
Changes between the last successful run and the first failing one:

* Update of GitHub Actions runner from 2.292.0 to 2.293.0
* Update of macOS-11 environment from 20220605.1 to 20220614.2
* Update of Python version from 3.10.4 to 3.10.5
* `certifi` 2022.5.18.1 –> 2022.6.15
* `setuptools` 62.3.4 –> 62.6.0
* Previously it was building `macosx-10.15-x86_64-cpython-310` wheels now it is building `macosx-10.15-universal2-cpython-310` wheels.

According to the previous commits downgrading `setuptools` and `certifi` does not help.

**Comment by icemac** [comment]
Rerunning a job which successfully ran 14 days ago now also fails.

**Comment by icemac** [comment]
I have no idea how to debug this issue and what could be the reason behind it.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2022-6-20 00:06 -0700:
>I have no idea how to debug this issue and what could be the reason behind it.

The problem is a failing `os.rename(dist_info, egg_info)` with
the error message `Directory not empty`.
I suppose that `egg_info` already exists; the rename therefore includes
its implicit `unlink`. This fails because `egg_info` is not empty.

I do not know why the target already exists -- maybe a leftover
from a previous run. It might help to remove the `.eggs` folder
at the start of the build.

**Comment by icemac** [comment]
Hm, trying to remove the .eggs directory does not seem to help.

**Comment by d-maurer** [comment]
> There might be 2 different trials to install `zope.proxy`: `zope.security`'s `setup.py` has `zope.proxy` both in `setup_requires` and `install_requires`. Not sure why this should make a problem under MaxOS but not elsewhere.

Locally (Linux), I have instrumented `setuptools.wheel.Wheel._convert_metadata`:
`from pdb import Pdb; t = os.open(tty, os.O_RDWR); D=Pdb(stdin=os.fdopen(t), stdout=os.fdopen(t, "w")); D.set_trace()` with *tty* the result of the `tty` command. This allows to debug the problematic `_convert_metadata`. In my environment, `zope.proxy` is installed only once (to satisfy `setup_requires`); apparently, `setuptools` correctly recognizes that `zope.proxy` is already available and does not try a second installation for `install_requires`.

I have no MaxOS system to do something similar for it.

**Comment by icemac** [comment]
Hm setting `_PYTHON_HOST_PLATFORM="macosx-11-x86_64"` fixes the build issue but later on the wheel cannot be downloaded to test it.

It is probably the time to invest into using cibuildwheel instead of our homegrown solution, see https://github.com/zopefoundation/ExtensionClass/pull/39

**Comment by icemac** [comment]
Now it just seems to be a problem with https://coveralls.io which is down for maintenance.

**Comment by icemac** [comment]
Wow, GHA is green now! No I have to port the changes to meta/config so the other projects can benefit.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2022-6-21 23:15 -0700:
>Hm, trying to remove the .eggs directory does not seem to help.

The problem apparently arises for the `zope.proxy` dependency
installation.
Can `zope.proxy` be correctly build for the platform and Python version?
Have other packages depending on `zope.proxy` the same problem?

I can see 2 potential causes:
 * the `zope.proxy` distribution unexpectedly contains the "egg-info" folder
   which may confuse `setuptools`
 * there are 2 dependency paths to `zope.proxy` and
   the second installation trial fails because the first one
   has created the "egg-info" folder
   (this would indicate a `setuptools` bug: it should have
   noticed that it has already installed `zope.proxy`).

**Pull request merged**
