### PR TITLE
Windows GHA

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by dataflake** [comment]
It looks like the definition for `macos-latest` has changed since last week when the tests ran fine on this branch. It moved from version 12.7.4 to version 14.4.1.

The macOS 12.7.4 runners apparently had pre-installed binaries for Python 3.7 through 3.12, the Python setup action did not have to check the versions manifest (https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) to find suitable downloads.

The macOS 14.4.1 runner only has Python 3.11 and up pre-installed, all older versions are downloaded and built with data from the Python versions manifest. This version manifest shows no arm64 Python 3.7 build.

A solution could be to force the older macOS runner for Python 3.7 or drop building wheels and testing for Python 3.7 on macOS.

**Comment by icemac** [comment]
Maybe it is time to drop support for Python 3.7, as it has reached its end of life at 2023-06-27.

**Comment by icemac** [comment]
@dataflake But for now it seems to be easier to fix it like you suggested. We have to many open issues to also add dropping 3.7 support right now.

**Comment by dataflake** [comment]
Can you remind me since this `macos-latest` is not in the meta repo `master`: Did you use some meta repo branch to create the test matrix here?

**Comment by icemac** [comment]
@dataflake I am using https://github.com/zopefoundation/meta/pull/207 here and my current goal is to make it ready to be merged.

**Comment by dataflake** [comment]
OK, I'll add the changes there and run it against this package again

**Comment by dataflake** [comment]
With the change in https://github.com/zopefoundation/meta/pull/207/commits/c0bfa85b9df330d7571221c3dfb1cf44166bb80c the build and test runs again. When this is merged the branch protection rule for `master` in this repository needs to be changed, it still expects a check for Python 3.7 on macos-latest.

**Review by dataflake — APPROVED** [review]

**Pull request merged**
